import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  LoginMainView: {
    flex: 1,
    backgroundColor: 'red',
  },
  text: {
    color: '#000',
    fontSize: 37,
    textAlign: 'left',
    marginTop: 25,
    textAlign: 'center',
    fontWeight: '700',
  },
  textlogin: {
    color: '#000',
    fontSize: 37,
    textAlign: 'left',
    marginTop: 25,
    textAlign: 'center',
    fontWeight: '400',
  },
  ptext: {
    color: '#000',
    fontSize: 18,
    textAlign: 'left',
    marginTop: 10,
    textAlign: 'center',
    padding: 10,
  },
  textinput: {
    backgroundColor: 'white',
    marginTop: 20,
    padding: 20,
    borderRadius: 8,
    borderColor: '#000',
    borderWidth: 0.6,
    borderColor: 'black',
    color: 'black',
  },
  submitBtm: {
    color: '#000',
    fontSize: 18,
    backgroundColor: 'green',
    borderRadius: 10,
    paddingTop: 15,
    paddingBottom: 10,
    marginTop: 5,

    shadowColor: 'white',
    shadowOffset: {height: 3, width: 3},
    shadowOpacity: 1.5,
    shadowRadius: 3,
  },
  loader: {
    minHeight: '100%',
    justifyContent: 'center',
    position: 'absolute',
    alignSelf: 'center',
    textAlignVertical: 'center',
    marginTop: '50%',
  },
  LogoImage: {
    height: 150,
    width: 200,
    alignSelf: 'center',
    marginTop: '30%',
  },
  DelightModelView: {
    marginTop: '40%',
    width: '80%',
    alignSelf: 'center',
    borderColor: 'grey',
    borderWidth: 0.5,
    padding: '5%',
    backgroundColor: 'rgba(245, 245, 245, 1)',
    borderRadius: 20,
  },
  DelightModelText: {
    alignSelf: 'center',
    margin: '5%',
    fontSize: 20,
    fontFamily:'Georgia',
    fontWeight:'500',
    color: 'black',  
  },
  StoreOtpBtn: {
    flexDirection: 'row',
    justifyContent:'flex-start',
    borderColor: 'black',
    borderWidth: 0.3,
    padding: '2%',
    margin: '1%',
    borderRadius: 15,
  },
  OtpTextInputStyle: {
    borderColor: 'black',
    borderWidth: 0.7,
    width: '90%',
    padding: '4%',
    marginVertical: '2%',
    fontSize: 17,
    borderRadius: 10,
    overflow: 'hidden',
    alignSelf: 'center',
  },
  LoginOtpBtn: {
    alignItems: 'center',
    marginHorizontal: '10%',
    marginVertical: '5%',
    // borderColor: 'grey',
    // borderWidth: 0.5,
    padding: '4%',
    borderRadius: 20,
    backgroundColor: '#3399ff',
    marginTop:15
  },
  OtpValidationView: {
    alignItems: 'center',
    marginHorizontal: '10%',
    marginVertical: '5%',
    // borderColor: 'grey',
    // borderWidth: 0.5,
    padding: '4%',
    borderRadius: 20,
    backgroundColor: '#a6a6a6',
    marginTop:15
  },
  ModelPressableBtn: {
    alignItems: 'center',
    marginHorizontal: '10%',
    // marginVertical: '5%',
    borderColor: '#ff0000',
    borderWidth: 1,
    padding: '2%',
    borderRadius: 30,
    backgroundColor: '#fff',marginTop:20
  },
  PosForRetailText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#103459',
    alignSelf: 'center',
    letterSpacing: 1,
  },
  LoginText: {
    color: 'white',
    fontSize: 35,
    fontWeight: 'bold',
    alignSelf: 'center',
    paddingTop: '40%',
  },
  SignIntoContinueText: {
    color: 'white',
    fontSize: 15,
    fontWeight: '500',
    alignSelf: 'center',
  },
  UserNameTxtInput: {
    backgroundColor: 'white',
    width: '70%',
    alignSelf: 'center',
    padding: '3%',
    marginVertical: '2%',
    fontSize: 16,
    borderRadius: 15,
    overflow: 'hidden',
    marginTop:'15%'
  },
  LoginPasswordTxtInput: {
    backgroundColor: 'white',
    alignSelf: 'center',
    width: '70%',
    padding: '3%',
    marginVertical: '2%',
    fontSize: 17,
    borderRadius: 15,
    marginTop:15
  },
  PasswordTxtInput: {
    backgroundColor: 'white',
    alignSelf: 'center',
    width: '80%',
    padding: '3%',
    marginVertical: '2%',
    fontSize: 16,
    borderRadius: 10,
  },
  CheckBoxView: {
    paddingTop: 0,
    paddingBottom: 10,
    display: 'flex',
    marginTop: 10,
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
  },
  TCText: {
    color: 'white',
    paddingTop: 5,
    paddingLeft: 5,
    // width:'60%'
    fontSize:12,
  },
  TCTextForLinking: {
    paddingTop: 3,
    paddingLeft: 5,
    color: 'blue',
    textDecorationLine: 'underline',
    fontSize: 16,
    fontWeight: '700',
  },
  LoginBtnView: {
    alignSelf: 'center',
    marginBottom: '27%',
    width: '60%',
  },
  LoginBtnText: {
    fontSize: 20,
    textAlign: 'center',
    fontWeight: '700',
  },
  LoadingPageView: {
    width: '100%',
    position: 'absolute',
    backgroundColor: '#000000ab',
    height: '100%',
  },
  activityIndicator: {
    backgroundColor: '#fff',
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    height: '0%',
  },

  focused: {
    borderColor: '#3784fd',
    borderWidth: 1,
  },
  blurred: {
    borderColor: '#b5b5b5',
  },
  centeredView: {
    // backgroundColor: 'rgba(0,0,0,0.5)',
    backgroundColor:'white',
    flex: 1,
  },

  modelContainer: {
    flex: 1,
    // alignItems: 'center',
    // justifyContent: 'center',
    marginTop: Platform.OS === 'android' ? -40 : 20,
    backgroundColor: 'white',
  },

  ModalTextInput: {
    borderColor: '#000',
    color: '#000',
    fontSize: 16,
    padding: '2%',
    fontWeight: '300',
    width: '50%',
    alignSelf: 'center',
    backgroundColor: 'white',
    borderWidth: 0.4,
    borderRadius: 10,
    marginVertical: '2.5%',
  },

  closeButton: {
    color: 'red',
    fontSize: 30,
    margin: 15,
    textAlign: 'right',
  },

  textName: {
    marginTop: Platform.OS === 'android' ? 10 : 10,
    color: '#000',
    fontWeight: '500',
    fontSize: 16,
    textAlign: 'center',
    borderColor: '#adadad',
    borderWidth: 1,
    alignSelf: 'center',
    padding: '2%',
    borderRadius: 10,
  },

  textBarcode: {
    marginTop: 10,
    color: 'grey',
    textAlign: 'center',
    fontWeight: '500',
  },
  textForPromotionAlert: {
    marginTop: 10,
    color: 'red',
    textAlign: 'center',
    fontWeight: '500',
    fontSize:14
  },

  horizontalLine: {
    margin: 10,
    marginTop: Platform.OS === 'android' ? 20 : 10,
    marginBottom: Platform.OS === 'android' ? 15 : 5,
    marginBottom: 15,
    borderBottomWidth: 0.5,
    borderBottomColor: 'grey',
  },

  textStyle: {
    margin: 8,
    marginRight: 5,
    color: 'grey',
    fontSize: 16,
    fontWeight: '500',
  },

  textColon: {
    margin: 8,
    marginRight: 5,
    color: 'grey',
    fontSize: 16,
    fontWeight: '500',
  },

  textInputPrice: {
    color: '#3784fd',
    fontSize: 16,
    borderColor: 'grey',
    marginLeft: 10,
    borderWidth: 0.5,
    fontWeight: '500',
    padding: 5,
    width: 130,
    borderRadius: 10,
  },

  textChangeExpiryDate: {
    color: '#3784fd',
    fontSize: 16,
    fontWeight: '500',
  },

  image: {
    width: 18,
    height: 18,
    alignItems: 'flex-end',
    marginLeft: 10,
    tintColor: 'grey',
    alignContent: 'center',
  },

  submitBtm: {
    color: '#000',
    fontSize: 18,
    borderRadius: 10,
    padding: 10,
    backgroundColor: '#3784fd',
    margin: 20,
    // marginTop: Platform.OS === 'android' ? -30 : -20,
    // marginBottom: Platform.OS === 'android' ? 10 : 10,
  },

  textButton: {
    fontSize: 18,
    color: '#fff',
    textAlign: 'center',
  },

  modalText: {
    textAlign: 'center',
    fontSize: 16,
    color: 'grey',
    fontWeight: 'bold',
  },

  btnText: {
    color: '#228B22',
    fontSize: 15,
    marginTop: '50%',
    fontWeight: '500',
    textAlign: 'center',
  },
  button: {
    backgroundColor: '#3478F5',
    padding: 10,
    borderRadius: 5,
  },
  buttonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  EbtButtons: {
    flexDirection: 'row',
    justifyContent: "space-between",
    borderColor: 'grey',
    borderWidth: 0.5,
    alignSelf: 'center',
    alignItems: 'center',
    padding: '1%',
    borderRadius: 15,
    marginVertical: '1%',
    width: '85%',
  },
});
